name: Maintenance

on:
  schedule:
    - cron: '30 1 * * *' # 8:30am everyday in PAST
  workflow_dispatch:

jobs:
  close-stale-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Close Stale Issues
        uses: actions/stale@v5.0.0
        with:
          days-before-issue-stale: 120
          days-before-pr-stale: 120
          operations-per-run: 200
    permissions:
      issues: write
      pull-requests: write
